# Generated by Django 5.1.1 on 2024-10-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='عنوان در Url')),
                ('is_sub', models.BooleanField(default=False, verbose_name='آیا یک زیر دسته است ؟')),
                ('image', models.ImageField(upload_to='medias/products/categories', verbose_name='تصویر دسته بندی')),
                ('sub_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.productcategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'db_table': 'product_category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='عنوان در Url')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا موجود است ؟')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('image', models.ImageField(upload_to='medias/products', verbose_name='تصویر محصول')),
                ('sub_categories', models.ManyToManyField(related_name='p_category', to='product.productcategory', verbose_name='دسته بندی های محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'db_table': 'products',
                'ordering': ['title'],
            },
        ),
    ]
