# Generated by Django 5.1.1 on 2024-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='product_per_category',
            field=models.ManyToManyField(related_name='c_products', to='product.productcategory', verbose_name='دسته بندی های محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medias/products', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medias/products/categories', verbose_name='تصویر دسته بندی'),
        ),
    ]
